### PR TITLE
Introduce multi targets and probability matrices

### PR DESCRIPTION
**Pull request by bytesnake**
This PR introduces multi-target datasets and makes it easier to work with the `Dataset` API. 

## Changes to datasets
 * rename `Targets` to `AsTargets` and introduce `AsTargetsMut` for mutable borrowing and `FromTargetArray` for counted labels construction
 * default to multi-target datasets in `pub type Dataset..`
 * re-name `observations` to `nsamples` and add `ntargets`
 * rename `frequencies_with_mask` to `label_frequencies_with_mask`
 * add `sample_iter`, `target_iter`, `feature_iter` iterators
 * rename `axis_chunks_iter` to `sample_chunks`
 * rename `bootstrap` to `bootstrap_samples` and add `bootstrap` (simultaneously sample features and samples) and `bootstrap_features`
 * add a `try_single_target -> Result<..>` which may return an `Error::MultipleTargets` for use in ROC/SVM/etc.
 * add `FromTarget` in order to accept `Array1` in `Dataset::new` and use `Targets == Array2<()>` for empty targets
 * add `PredictRef` which is used by a "proxy" trait `Predict` to derive all possible input/output combinations

## Other changes
 * add tests to `linfa-datasets`
 * add error types with `thiserror` where possible

## Updates for sub-crates
 * [x] linfa-reduction
 * [x] linfa-elasticnet
 * [x] linfa-bayes
 * [x] linfa-clustering
 * [x] linfa-hierarchical
 * [x] linfa-kernel
 * [x] linfa-linear
 * [x] linfa-ica
 * [x] linfa-logistic
 * [x] linfa-svm
 * [x] linfa-trees

## Other changes
 * [x] explain mechanism and difference between `Predict` and `PredictRef` in `CONTRIBUTION.md`
 * [x] improve implementation of `src/metrics_regression.rs` to accept `DatasetBase` variants
 * [x] add wrapper `MultiTargetModel` which can merge multiple single-target models 
 * [ ] (improve story around `DatasetPr`, probably in a later PR)

### CODE REVIEW

**Comment by bytesnake** [comment]
@Sauro98 do you have time to review this? Otherwise I would just merge it

**Comment by Sauro98** [comment]
No, not right now, I have a final coming up on Tuesday so I'll still be pretty busy for a few days, sorry. I gave it a (very very quick) look at the proposed changes and I'd say great work 💪🏻. I especially like the idea of the `Predict` and `PredictRef` traits

**Comment by relf** [comment]
FWIW, it looks great for me as well. I should say I learn a lot about Rust programming thanks to you! :sweat_smile:

**Comment by bytesnake** [comment]
> No, not right now, I have a final coming up on Tuesday so I'll still be pretty busy for a few days, sorry. I gave a (very very quick) look at the proposed changes and I'd say great work 💪🏻. I especially like the idea of the `Predict` and `PredictRef` traits

okay, good luck for the exam :+1: 

> FWIW, it looks great for me as well. I should say I learn a lot about Rust programming thanks to you! :sweat_smile:

not only you, the Rust type and lifetime system is sometimes tough :laughing:

**Pull request merged**
