### PR TITLE
[WIP] Enable Code Coverage with tarpaulin

### PR DESCRIPTION
**Pull request by paulkoerbitz**
Attempt to enable code coverage using tarpaulin as per #35. Currently failing

### CODE REVIEW

**Comment by paulkoerbitz** [comment]
@xd009642 I'm looking for some help debugging the tarpaulin build - maybe you could give me a hint?

Running `cargo tarpaulin --all -v --run-types Tests Doctests` in this repo fails, I haven't been able to really figure out what the issue is.

Running the command prefixed with `strace` (so `strace cargo tarpaulin --all -v --run-types Tests Doctests`) I get the following hints for the error:

```
read(4,    Compiling linfa-reduction v0.1.0 (/home/travis/build/rust-ml/linfa/linfa-reduction)
2078"{\"reason\":\"compiler-artifact\",\"p"..., 8192) = 660
2079read(4, "{\"reason\":\"compiler-message\",\"pa"..., 8192) = 8192
2080read(4, "avis/build/rust-ml/linfa/target/"..., 8192) = 8192
2081read(4, "74083e.rlib\\\" \\\"/home/travis/.ru"..., 8192) = 8192
2082read(4, "     /home/travis/.cargo/registr"..., 8192) = 8192
2083read(4, "APACKE_cgbsvxx_work'\\n          "..., 8192) = 8192
2084read(4, "rc/lib.rs:52985: undefined refer"..., 8192) = 8192
2085read(4, "ome/travis/build/rust-ml/linfa/t"..., 8192) = 8192
2086read(4, ".rlib\\\" \\\"/home/travis/build/rus"..., 8192) = 8192
2087read(4, "f60ce605806':\\n/home/travis/.car"..., 8192) = 8192
2088read(4, "n function `lapacke::zgbrfsx_wor"..., 8192) = 8192
2089read(4, "stry/src/github.com-1ecc6299db9e"..., 8192) = 2987
2090wait4(10084, error: could not compile `linfa-linear`.
```

So it seams that there is some linking error with lapacke.

Could you give me a hint how I could debug this issue better? `cargo tarpaulin -v` isn't very verbose, I'm looking for some way to tease more information out of it.

**Comment by xd009642** [comment]
`cargo tarpaulin --debug` is a lot more verbose. There can be some linking issues with libraries using FFI which is what I suspect is happening here, one solution to that might be to change the backend ndarray-linalg is using for the development profile. (I'm guessing that's what's bringing in lapacke)

**Comment by paulkoerbitz** [comment]
Thank you @xd009642, I will give this a shot!

**Comment by bytesnake** [comment]
closing this because we are switching to Github actions

**Pull request closed without merging**
