### PR TITLE
Bump ndarray to 0.15.0

### PR DESCRIPTION
**Pull request by YuhanLiin**
Addresses #124.
Having issues with new version of `sprs`. The compile error most likely has something to do with https://github.com/vbarrielle/sprs/issues/278 and was introduced by https://github.com/vbarrielle/sprs/pull/290.

### CODE REVIEW

**Comment by bytesnake** [comment]
replacing the operator with `sprs::binop::csmat_binop(mat.view(), mat.transpose_view(), |x, y| x.add(*y));` seems to work as a workaround. The difference between making the explicit call to `add` and the operator makes the difference: https://docs.rs/sprs/0.11.0/src/sprs/sparse/binop.rs.html#63

**Comment by bytesnake** [comment]
the construction of the sparse matrix fails though and I'm not yet sure why

**Comment by bytesnake** [comment]
the new constructor assumes ordered indices, this solves it:
```rust
    // create CSR matrix from data, indptr and indices
    let mat = CsMatBase::new_from_unsorted((n_points, n_points), indptr, indices, data).unwrap();
    let mut mat = sprs::binop::csmat_binop(mat.view(), mat.transpose_view().to_other_storage().view(), |x, y| x.add(*y));
```

**Comment by mulimoen** [comment]
It seems there are some strange type inference going on when using `linfa::Float` in `sprs`. You can use the following code instead:
```rust
    // create CSR matrix from data, indptr and indices
    let mat = CsMat::<F>::new_from_unsorted((n_points, n_points), indptr, indices, data).unwrap();
    let transpose = mat.transpose_view().to_other_storage();
    sprs::binop::csmat_binop(mat.view(), transpose.view(), |_, _| F::one())
```
This does the same as we do behind the scene. I have assumed `x + y != 0`, and moved this computation into `binop`, which might be more performant

**Review by bytesnake — APPROVED** [review]
:+1:

**Comment by bytesnake** [comment]
the CI pipeline somehow failed to run here as well, I checked manually ..

**Pull request merged**
