### PR TITLE
Enable serde features for all applicable crates in new CI checking step

### PR DESCRIPTION
**Pull request by YuhanLiin**
Addresses #135

### CODE REVIEW

**Comment by YuhanLiin** [comment]
Apparently some of the code doesn't compile with `serde` unless I implement Serde traits on `linfa::Error`. Don't know if I should actually do that.

**Comment by bytesnake** [comment]
> Apparently some of the code doesn't compile with `serde` unless I implement Serde traits on `linfa::Error`. Don't know if I should actually do that.
> The issue is that `ElasticNet` stores a `Result`, so Serde impls are required on the error type to be derived on `ElasticNet`. I'm not sure why `ElasticNet` stores a `Result` in the first place.

then let's just add a serde feature flag for the base crate and just use it in downstream crates, I didn't foresee that .. `linfa-pls` is also complaining that imports are missing

**Comment by YuhanLiin** [comment]
This doesn't work because one of the variants of `linfa::Error` contains an external type (`ShapeError`) that doesn't implement serde traits.

**Comment by YuhanLiin** [comment]
@bytesnake For MSRV testing using Rust version 1.42.0 does the version of Cargo also need to be set at 1.42.0 (which it is right now) or can we use the latest Cargo? I'm running into CI issues that I believe are being caused by outdate Cargo.

**Comment by bytesnake** [comment]
> This doesn't work because one of the variants of `linfa::Error` contains an external type (`ShapeError`) that doesn't implement serde traits.

then let's skip this variant for the time being

> @bytesnake For MSRV testing using Rust version 1.42.0 does the version of Cargo also need to be set at 1.42.0 (which it is right now) or can we use the latest Cargo? I'm running into CI issues that I believe are being caused by outdate Cargo.

you mean selecting features for members of workspace is not supported for 1.42.0? Perhaps you could drop the separate serde features and just depend on `linfa/serde` in the subcrates

**Comment by YuhanLiin** [comment]
I don't believe it's possible to conditionally compile code using features in dependency crates. Something like `cfg("linfa/serde")` wouldn't work in the algorithm crates. My workaround for 1.42.0 is to just disable serde checking for that version entirely. If it works on 1.42.0 without serde and also on stable with serde then it probably works with serde on 1.42.0. Still much better than before in terms of serde checking.

**Comment by bytesnake** [comment]
> I don't believe it's possible to conditionally compile code using features in dependency crates. Something like `cfg("linfa/serde")` wouldn't work in the algorithm crates. My workaround for 1.42.0 is to just disable serde checking for that version entirely. If it works on 1.42.0 without serde and also on stable with serde then it probably works with serde on 1.42.0. Still much better than before in terms of serde checking.

indeed I searched for a solution but there is none.Then let's keep a separate feature flag for each subcrate. Can you merge the PR now?

**Review by bytesnake — APPROVED** [review]

**Pull request merged**
