### PR TITLE
use kdtree in appx dbscan

### PR DESCRIPTION
**Pull request by Sauro98**
I could not resist playing around with the new nn implementation 🤣 

I ran some very quick benchmarks and the difference is **huge**

Here are the results with the kdtree:
```bash
appx_dbscan/appx_dbscan/10                                                                            
                        time:   [54.991 us 55.731 us 56.593 us]
Found 15 outliers among 100 measurements (15.00%)
  9 (9.00%) high mild
  6 (6.00%) high severe
Benchmarking appx_dbscan/appx_dbscan/100: Warming up for 3.0000 s
Warning: Unable to complete 100 samples in 5.0s. You may wish to increase target time to 5.8s, enable flat sampling, or reduce sample count to 60.
appx_dbscan/appx_dbscan/100                                                                             
                        time:   [1.1207 ms 1.1449 ms 1.1715 ms]
Found 12 outliers among 100 measurements (12.00%)
  8 (8.00%) high mild
  4 (4.00%) high severe
Benchmarking appx_dbscan/appx_dbscan/1000: Warming up for 3.0000 s
Warning: Unable to complete 100 samples in 5.0s. You may wish to increase target time to 6.7s, or reduce sample count to 70.
appx_dbscan/appx_dbscan/1000                                                                            
                        time:   [65.097 ms 66.098 ms 67.174 ms]
Found 5 outliers among 100 measurements (5.00%)
  4 (4.00%) high mild
  1 (1.00%) high severe

```

And here are the results without kdtree:

```bash
appx_dbscan/appx_dbscan/10                                                                            
                        time:   [503.47 us 512.75 us 524.50 us]
                        change: [+830.13% +857.72% +894.77%] (p = 0.00 < 0.05)
                        Performance has regressed.
Found 3 outliers among 100 measurements (3.00%)
  1 (1.00%) high mild
  2 (2.00%) high severe
appx_dbscan/appx_dbscan/100                                                                            
                        time:   [5.8340 ms 5.9606 ms 6.0966 ms]
                        change: [+393.86% +413.88% +432.42%] (p = 0.00 < 0.05)
                        Performance has regressed.
Found 2 outliers among 100 measurements (2.00%)
  2 (2.00%) high mild
Benchmarking appx_dbscan/appx_dbscan/1000: Warming up for 3.0000 s
Warning: Unable to complete 100 samples in 5.0s. You may wish to increase target time to 10.0s, or reduce sample count to 50.
appx_dbscan/appx_dbscan/1000                                                                            
                        time:   [94.151 ms 95.906 ms 97.774 ms]
                        change: [+41.652% +45.096% +48.809%] (p = 0.00 < 0.05)
                        Performance has regressed.
Found 3 outliers among 100 measurements (3.00%)
  3 (3.00%) high mild
```

All tests are still passing, but I should runs some more benches to ensure that the enormous performance boost I got was not just my machine acting weird

### CODE REVIEW

**Comment by bytesnake** [comment]
should the speedup not increase with the number of samples? Really cool to see those come together :+1:

**Comment by Sauro98** [comment]
It should, I should play with the parameters and also find a way to avoid allocating a whole new array2 for the indices and casting back and forth from float to i64

**Comment by YuhanLiin** [comment]
I'm working on integrating NN into DBSCAN and unfortunately I need to make some breaking changes to the Nearest Neighbour trait APIs. If you want any breaking changes to NN that would make this PR easier then I could make those happen as well.

**Comment by YuhanLiin** [comment]
Solved by #178

**Pull request closed without merging**
